apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster-kops.yusufluai.my.id
  name: staging-node
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20211118
  machineType: t3.medium
  maxSize: 2
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: staging-node
    node: staging-node
  role: Node
  subnets:
  - ap-southeast-1a