apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend-svc
spec:
  clusterIP: 100.64.204.27
  selector:
    app: todo-app
    tier: backend
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000