apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-backend
  labels:
    app: todo-app
    tier: backend
spec:
  selector:
    matchLabels:
      app: todo-app
      tier: backend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-app
        tier: backend
    spec:
      containers:
      - name:  todo-app
        image:  yusufluai/mern-todo-app_server:latest
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: 250Mi
        #     memory: 250Mi
        #   limits:
        #     cpu: 1050Mi
        #     memory: 1050Mi
        env:
          - name: MONGO_URL
            value: "mongodb://mongo-service:27017/todos"
        ports:
        - containerPort: 4000
          protocol: TCP
      restartPolicy: Always