apiVersion: apps/v1
kind: Deployment
metadata:
  name:  admin-mongo
  labels:
    app: admin-mongo
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: admin-mongo
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  admin-mongo
    spec:
      containers:
      - name:  adminmongo
        image:  mrvautin/adminmongo:latest
        ports:
        - containerPort: 1234
          protocol: TCP
          name:  adminmongo
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: admin-mongo-svc
spec:
  selector:
    app: admin-mongo
  type: NodePort
  ports:
  - port: 1234
    targetPort: 1234
