apiVersion: apps/v1
kind: Deployment
metadata:
  name:  todo-app-database
  namespace: staging
  labels:
    app: todo-app
    tier: database
spec:
  selector:
    matchLabels:
      app: todo-app
      tier: database
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  todo-app
        tier: database
    spec:
      containers:
      - name:  mongodb
        image:  mongo:3.6.19-xenial
        # envFrom:
        #   - secretRef:
        #       name: mysecret
        ports:
        - containerPort: 27017
          protocol: TCP
          name:  mongodb
        # command:
        #   - [""]
        # args:
        #   - [""]
      # volumes:
      #   - name: my-claim
      #     persistentVolumeClaim:
      #       claimName: testing
    
      restartPolicy: Always